import {
  DEFAULT_SECTION_ORDER,
  INITIAL_RESUME_DATA,
  ResumeData,
  ResumeRecord,
} from '@/types/resume';

export const SAMPLE_ENGINEER_RESUME: ResumeData = {
  contact: {
    fullName: 'Alex Rivera',
    email: 'alex.rivera@example.com',
    phone: '+1 (555) 234-5678',
    location: 'San Francisco, CA',
    linkedinUrl: 'https://linkedin.com/in/alex-rivera',
    githubUrl: 'https://github.com/alexrivera-dev',
    portfolioUrl: 'https://alexrivera.tech',
  },
  summary: {
    text: 'Staff Software Engineer with 8+ years of experience spearheading distributed cloud systems, real-time data pipelines, and microservices at scale. Proven track record of boosting system reliability to 99.99% and mentoring high-velocity engineering teams.',
    visible: true,
  },
  experience: [
    {
      id: 'exp-1',
      visible: true,
      order: 0,
      company: 'Apex Cloud Systems',
      role: 'Staff Software Engineer',
      location: 'San Francisco, CA',
      startDate: '2022-03',
      endDate: '',
      current: true,
      bullets: [
        'Architected high-throughput event streaming platform handling 2.5B daily events, reducing p99 latency from 450ms to 85ms.',
        'Spearheaded Kubernetes zero-downtime migration across 45 microservices, cutting cloud infrastructure costs by $320K annually.',
        'Mentored 12 mid-level and senior engineers through design review cadences, accelerating sprint velocity by 28%.',
      ],
    },
    {
      id: 'exp-2',
      visible: true,
      order: 1,
      company: 'Pulse Analytics',
      role: 'Senior Backend Engineer',
      location: 'Seattle, WA',
      startDate: '2019-06',
      endDate: '2022-02',
      current: false,
      bullets: [
        'Engineered real-time telemetry processing engine in Go and Kafka, scaling data ingestion capacity by 400%.',
        'Implemented Redis caching cluster and connection pooling, slashing database query load by 60%.',
        'Designed automated CI/CD deployment pipeline with GitHub Actions, reducing release cycle time from 3 days to 40 minutes.',
      ],
    },
    {
      id: 'exp-3',
      visible: true,
      order: 2,
      company: 'NextGen Solutions',
      role: 'Full Stack Engineer',
      location: 'Austin, TX',
      startDate: '2017-08',
      endDate: '2019-05',
      current: false,
      bullets: [
        'Developed customer-facing analytics dashboard using Next.js, React, and TypeScript, used by 150K+ daily active users.',
        'Optimized PostgreSQL query schemas and indexing strategies, decreasing complex report generation time by 75%.',
      ],
    },
  ],
  projects: [
    {
      id: 'proj-1',
      visible: true,
      order: 0,
      name: 'StreamSync OSS',
      role: 'Creator & Maintainer',
      link: 'https://github.com/alexrivera-dev/streamsync',
      startDate: '2023-01',
      endDate: 'Present',
      technologies: ['TypeScript', 'Node.js', 'WebSockets', 'Redis'],
      bullets: [
        'Built lightweight open-source data synchronization engine with 3.2K+ GitHub stars and 50K+ monthly npm downloads.',
        'Authored comprehensive documentation and test suite achieving 98% test coverage.',
      ],
    },
    {
      id: 'proj-2',
      visible: true,
      order: 1,
      name: 'Distributed Lock Manager',
      role: 'Lead Developer',
      link: 'https://github.com/alexrivera-dev/dist-lock',
      startDate: '2022-04',
      endDate: '2022-11',
      technologies: ['Go', 'Raft', 'gRPC', 'Docker'],
      bullets: [
        'Implemented distributed consensus-based locking protocol with fault tolerance under network partition simulations.',
      ],
    },
  ],
  education: [
    {
      id: 'edu-1',
      visible: true,
      order: 0,
      institution: 'University of Washington',
      degree: 'Bachelor of Science',
      fieldOfStudy: 'Computer Science & Engineering',
      startDate: '2013-09',
      endDate: '2017-06',
      gpa: '3.85 / 4.00',
      honors: ["Dean's List (All Semesters)", 'Magna Cum Laude'],
    },
  ],
  skills: [
    {
      id: 'skill-1',
      visible: true,
      order: 0,
      categoryName: 'Languages & Runtimes',
      skills: ['TypeScript', 'JavaScript', 'Go', 'Python', 'Node.js', 'SQL', 'HTML5/CSS3'],
    },
    {
      id: 'skill-2',
      visible: true,
      order: 1,
      categoryName: 'Frameworks & Libraries',
      skills: ['React', 'Next.js', 'Express', 'FastAPI', 'Tailwind CSS', 'GraphQL', 'gRPC'],
    },
    {
      id: 'skill-3',
      visible: true,
      order: 2,
      categoryName: 'Cloud & Infrastructure',
      skills: ['AWS (EKS, S3, RDS, Lambda)', 'Docker', 'Kubernetes', 'Terraform', 'Kafka', 'Redis', 'PostgreSQL'],
    },
    {
      id: 'skill-4',
      visible: true,
      order: 3,
      categoryName: 'Methodologies & Practices',
      skills: ['System Architecture', 'CI/CD Pipelines', 'Microservices', 'Test-Driven Development', 'Agile/Scrum'],
    },
  ],
  certifications: [
    {
      id: 'cert-1',
      visible: true,
      order: 0,
      name: 'AWS Certified Solutions Architect - Professional',
      issuer: 'Amazon Web Services',
      issueDate: '2023-04',
      expirationDate: '2026-04',
      credentialUrl: 'https://aws.amazon.com/verification',
    },
    {
      id: 'cert-2',
      visible: true,
      order: 1,
      name: 'Certified Kubernetes Administrator (CKA)',
      issuer: 'Cloud Native Computing Foundation',
      issueDate: '2022-09',
      expirationDate: '2025-09',
    },
  ],
  involvement: [
    {
      id: 'inv-1',
      visible: true,
      order: 0,
      organization: 'Bay Area Tech Mentors',
      role: 'Volunteer Engineering Mentor',
      startDate: '2021-01',
      endDate: 'Present',
      bullets: [
        'Mentored 20+ underrepresented college students in algorithms, system design, and technical interview preparation.',
      ],
    },
  ],
  awards: [
    {
      id: 'awd-1',
      visible: true,
      order: 0,
      title: 'Apex Cloud Innovation Award',
      issuer: 'Apex Cloud Systems',
      date: '2023-12',
      description: 'Awarded for architectural breakthrough in real-time stream processing saving $320K/yr.',
    },
  ],
  publications: [
    {
      id: 'pub-1',
      visible: true,
      order: 0,
      title: 'Designing Zero-Downtime Microservice Migrations in Kubernetes',
      publisher: 'ACM Queue Software Engineering',
      date: '2023-08',
      url: 'https://queue.acm.org',
      authors: ['Alex Rivera', 'Elena Rostova'],
    },
  ],
  references: [],
};

export const SAMPLE_PRODUCT_RESUME: ResumeData = {
  contact: {
    fullName: 'Sarah Chen',
    email: 'sarah.chen@example.com',
    phone: '+1 (555) 876-5432',
    location: 'New York, NY',
    linkedinUrl: 'https://linkedin.com/in/sarahchen-pm',
  },
  summary: {
    text: 'Principal Product Manager with 7+ years of experience leading cross-functional teams in B2B SaaS and consumer fintech products. Generated $18M+ in new ARR by discovering product-market fit and executing data-driven roadmaps.',
    visible: true,
  },
  experience: [
    {
      id: 'exp-pm-1',
      visible: true,
      order: 0,
      company: 'FinVantage Group',
      role: 'Principal Product Manager',
      location: 'New York, NY',
      startDate: '2022-01',
      endDate: '',
      current: true,
      bullets: [
        'Spearheaded enterprise payment orchestration product from 0 to 1, capturing $12M ARR within 18 months of launch.',
        'Led cross-functional team of 16 engineers, 3 product designers, and 2 data scientists across 3 global regions.',
        'Increased user onboarding completion rate by 34% through A/B testing self-serve verification workflows.',
      ],
    },
    {
      id: 'exp-pm-2',
      visible: true,
      order: 1,
      company: 'Nova Commerce',
      role: 'Senior Product Manager',
      location: 'Boston, MA',
      startDate: '2018-09',
      endDate: '2021-12',
      current: false,
      bullets: [
        'Owned merchant checkout experience generating $450M in annual GMV across 2,400 active retailers.',
        'Reduced cart abandonment rate by 18% via streamlined 1-click checkout flow and localized payment methods.',
      ],
    },
  ],
  projects: [],
  education: [
    {
      id: 'edu-pm-1',
      visible: true,
      order: 0,
      institution: 'Columbia Business School',
      degree: 'Master of Business Administration (MBA)',
      fieldOfStudy: 'Strategy & Innovation',
      startDate: '2016-09',
      endDate: '2018-05',
    },
    {
      id: 'edu-pm-2',
      visible: true,
      order: 1,
      institution: 'Cornell University',
      degree: 'Bachelor of Science',
      fieldOfStudy: 'Information Science',
      startDate: '2012-09',
      endDate: '2016-05',
    },
  ],
  skills: [
    {
      id: 'skill-pm-1',
      visible: true,
      order: 0,
      categoryName: 'Product Strategy & Discovery',
      skills: ['Product Lifecycle Management', 'Roadmap Planning', 'User Research', 'A/B Testing', 'Go-To-Market (GTM)'],
    },
    {
      id: 'skill-pm-2',
      visible: true,
      order: 1,
      categoryName: 'Analytics & Tools',
      skills: ['SQL', 'Mixpanel', 'Amplitude', 'Jira', 'Figma', 'Tableau', 'Google Analytics'],
    },
  ],
  certifications: [],
  involvement: [],
  awards: [],
  publications: [],
  references: [],
};

export const SAMPLE_EXECUTIVE_RESUME: ResumeData = {
  contact: {
    fullName: 'Marcus Vance',
    email: 'marcus.vance@example.com',
    phone: '+1 (555) 901-2345',
    location: 'Chicago, IL',
    linkedinUrl: 'https://linkedin.com/in/marcus-vance',
  },
  summary: {
    text: 'Chief Technology Officer with 15+ years of engineering leadership, corporate technology transformation, and hyper-growth scaling. Built and led 120+ engineer organizations, driving $100M+ enterprise platform valuations.',
    visible: true,
  },
  experience: [
    {
      id: 'exp-exec-1',
      visible: true,
      order: 0,
      company: 'Aetheris Enterprises',
      role: 'Chief Technology Officer',
      location: 'Chicago, IL',
      startDate: '2020-05',
      endDate: '',
      current: true,
      bullets: [
        'Transformed legacy monolithic architecture into high-performing event-driven cloud ecosystem, reducing operational overhead by 42%.',
        'Grew engineering and product organization from 28 to 135 professionals with a 94% retention rate over 4 years.',
        'Partnered with CEO and Board of Directors to execute Series C and D fundraising rounds totaling $85M.',
      ],
    },
  ],
  projects: [],
  education: [
    {
      id: 'edu-exec-1',
      visible: true,
      order: 0,
      institution: 'Northwestern University',
      degree: 'Master of Science',
      fieldOfStudy: 'Computer Science',
      startDate: '2006-09',
      endDate: '2008-06',
    },
  ],
  skills: [
    {
      id: 'skill-exec-1',
      visible: true,
      order: 0,
      categoryName: 'Executive Leadership',
      skills: ['Enterprise Architecture', 'M&A Technical Due Diligence', 'Budget & P&L Management ($30M+)', 'Global Talent Acquisition'],
    },
  ],
  certifications: [],
  involvement: [],
  awards: [],
  publications: [],
  references: [],
};

export const SAMPLE_IQBAL_HASAN_RESUME: ResumeData = {
  contact: {
    fullName: 'Iqbal Hasan',
    email: 'iqbalhasan.dev@gmail.com',
    phone: '+880 1762 445377',
    location: 'Dhaka, Bangladesh',
    linkedinUrl: 'https://linkedin.com/in/iqbalhasandev',
    githubUrl: 'https://github.com/iqbalhasandev',
    portfolioUrl: 'https://iqbalhasan.dev',
  },
  summary: {
    text: 'Software Engineer with 6+ years of experience building scalable SaaS platforms, ERP systems, and AI-enabled products. Currently building HRIS and microservice platforms using Node.js, NestJS, Next.js, and TypeScript, with extensive experience in PHP/Laravel backend architecture, React/Inertia.js, and custom AI agent workflows (MCP, multi-model providers, prompt automation).',
    visible: true,
  },
  experience: [
    {
      id: 'exp-iqbal-1',
      visible: true,
      order: 0,
      company: 'Shomvob Ltd.',
      role: 'Software Development Engineer II (SDE II)',
      location: 'Dhaka, Bangladesh (On-site)',
      startDate: '2026-06',
      endDate: '',
      current: true,
      bullets: [
        'Architect and develop Human Resource Information System (HRIS) backend microservices in Node.js/NestJS and Next.js TypeScript frontends.',
        'Implement AI-powered automation workflows within the HRIS platform, improving workflow efficiency and smart task scheduling.',
        'Design REST API contracts, service boundaries, and inter-service communication protocols across distributed services.',
        'Leverage AI-assisted tooling (Claude, GitHub Copilot) and MCP tooling to accelerate feature delivery cycles and maintain high code quality.',
      ],
    },
    {
      id: 'exp-iqbal-2',
      visible: true,
      order: 1,
      company: 'Nextbit Studio LLC',
      role: 'Software Engineer',
      location: 'Remote',
      startDate: '2024-12',
      endDate: '2026-05',
      current: false,
      bullets: [
        'Led engineering for managed hosting SaaS platform (WC Studio), building server provisioning pipelines, site isolation, and automated SSL lifecycle management.',
        'Designed and shipped custom AI agents and multi-model LLM integrations for in-app automation and intelligent assistant workflows.',
        'Implemented Model Context Protocol (MCP) integrations connecting AI systems directly with developer tooling and operational infrastructure.',
        'Engineered high-concurrency backend services using PHP, Laravel, React, Inertia.js, MySQL, and Redis.',
      ],
    },
    {
      id: 'exp-iqbal-3',
      visible: true,
      order: 2,
      company: 'Bdtask Ltd.',
      role: 'Laravel Developer',
      location: 'Dhaka, Bangladesh',
      startDate: '2023-02',
      endDate: '2024-11',
      current: false,
      bullets: [
        'Delivered feature enhancements across enterprise ERP platforms (Gold ERP, AI-Guru) covering Inventory, HRM, Accounting, and CRM modules.',
        'Integrated ChatGPT and generative AI APIs for automated business reports, data extraction, and content generation workflows.',
        'Refactored legacy workflow logic and optimized MySQL database indexing, reducing query execution times by 40%.',
      ],
    },
    {
      id: 'exp-iqbal-4',
      visible: true,
      order: 3,
      company: 'Devzar',
      role: 'Software Engineer',
      location: 'Dhaka, Bangladesh',
      startDate: '2021-12',
      endDate: '2023-01',
      current: false,
      bullets: [
        'Developed and maintained custom SaaS solutions for retail, education, healthcare, and logistics (POS, Pharmacy, Diagnostic, and Courier systems).',
        'Implemented full-stack modules with PHP, Laravel, JavaScript, MySQL, and Bootstrap with CI/CD deployment pipelines.',
      ],
    },
  ],
  projects: [
    {
      id: 'proj-iqbal-1',
      visible: true,
      order: 0,
      name: 'Shomvob HRIS',
      role: 'Core Backend & AI Engineer',
      link: 'https://hr.shomvob.com',
      startDate: '2026-06',
      endDate: 'Present',
      technologies: ['Node.js', 'NestJS', 'Next.js', 'TypeScript', 'Microservices', 'AI Automation'],
      bullets: [
        'Microservice-based Human Resource Information System with AI-powered workflow automations and role-based permissions.',
      ],
    },
    {
      id: 'proj-iqbal-2',
      visible: true,
      order: 1,
      name: 'WC Studio',
      role: 'Lead Full Stack Engineer',
      link: 'https://wcstudio.com',
      startDate: '2024-12',
      endDate: '2026-05',
      technologies: ['Laravel', 'PHP', 'React', 'Inertia.js', 'Redis', 'MySQL', 'MCP', 'AI Agents'],
      bullets: [
        'Managed hosting SaaS platform covering automated server provisioning, site isolation, SSL lifecycle, and billing workflows.',
      ],
    },
    {
      id: 'proj-iqbal-3',
      visible: true,
      order: 2,
      name: 'PromptForm',
      role: 'Creator & Developer',
      link: 'https://promptform.app',
      startDate: '2024-06',
      endDate: 'Present',
      technologies: ['Next.js', 'TypeScript', 'OpenAI API', 'Claude', 'Tailwind CSS'],
      bullets: [
        'AI-driven platform for prompt-based form generation, structured data collection, and workflow automations.',
      ],
    },
  ],
  education: [
    {
      id: 'edu-iqbal-1',
      visible: true,
      order: 0,
      institution: 'Northern University Bangladesh',
      degree: 'Bachelor of Science (BSc)',
      fieldOfStudy: 'Computer Science & Engineering',
      startDate: '2023-01',
      endDate: 'Present',
    },
    {
      id: 'edu-iqbal-2',
      visible: true,
      order: 1,
      institution: 'Rajshahi Polytechnic Institute',
      degree: 'Diploma in Engineering',
      fieldOfStudy: 'Computer Engineering',
      startDate: '2017-08',
      endDate: '2022-06',
    },
  ],
  skills: [
    {
      id: 'skill-iqbal-1',
      visible: true,
      order: 0,
      categoryName: 'Languages & Core',
      skills: ['JavaScript', 'TypeScript', 'PHP', 'Python', 'SQL', 'HTML5/CSS3'],
    },
    {
      id: 'skill-iqbal-2',
      visible: true,
      order: 1,
      categoryName: 'Backend & Architecture',
      skills: ['Node.js', 'NestJS', 'Laravel', 'REST APIs', 'Microservices', 'JWT', 'WebSockets', 'MySQL', 'Redis'],
    },
    {
      id: 'skill-iqbal-3',
      visible: true,
      order: 2,
      categoryName: 'Frontend & UI',
      skills: ['React', 'Next.js', 'Inertia.js', 'Vue.js', 'Tailwind CSS', 'Bootstrap'],
    },
    {
      id: 'skill-iqbal-4',
      visible: true,
      order: 3,
      categoryName: 'AI & LLM Engineering',
      skills: ['OpenAI API', 'Claude', 'Prompt Engineering', 'AI Agent Workflows', 'MCP (Model Context Protocol)', 'AI Workflow Automation'],
    },
    {
      id: 'skill-iqbal-5',
      visible: true,
      order: 4,
      categoryName: 'DevOps & Tooling',
      skills: ['Docker', 'Linux', 'Git', 'GitHub Actions', 'CI/CD', 'AWS (basic)', 'Cloudflare'],
    },
  ],
  certifications: [],
  involvement: [
    {
      id: 'inv-iqbal-1',
      visible: true,
      order: 0,
      organization: 'AI Engineering & Open Source Community',
      role: 'Contributor & AI Agent Builder',
      startDate: '2024-01',
      endDate: 'Present',
      bullets: [
        'Designed and shipped custom AI agents and MCP tool implementations connecting LLMs to engineering work streams.',
      ],
    },
  ],
  awards: [],
  publications: [],
  references: [],
};

export const DEMO_RESUMES: ResumeRecord[] = [
  {
    id: 'demo-resume-iqbal',
    user_id: 'demo-user-1',
    title: 'Iqbal Hasan - SDE II & AI Integrations Resume',
    slug: 'iqbal-hasan-sde-ii',
    template_id: 'classic-ats',
    section_order: DEFAULT_SECTION_ORDER,
    content: SAMPLE_IQBAL_HASAN_RESUME,
    ats_score: 98,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-resume-1',
    user_id: 'demo-user-1',
    title: 'Senior Software Engineer (ATS Target)',
    slug: 'senior-software-engineer',
    template_id: 'classic-ats',
    section_order: DEFAULT_SECTION_ORDER,
    content: SAMPLE_ENGINEER_RESUME,
    ats_score: 94,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: 'demo-resume-2',
    user_id: 'demo-user-1',
    title: 'Principal Product Manager - FinTech',
    slug: 'principal-product-manager',
    template_id: 'modern-minimal',
    section_order: DEFAULT_SECTION_ORDER,
    content: SAMPLE_PRODUCT_RESUME,
    ats_score: 88,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
  },
  {
    id: 'demo-resume-3',
    user_id: 'demo-user-1',
    title: 'CTO / VP of Engineering Executive Resume',
    slug: 'executive-cto-resume',
    template_id: 'executive',
    section_order: DEFAULT_SECTION_ORDER,
    content: SAMPLE_EXECUTIVE_RESUME,
    ats_score: 96,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
  },
];
